runtime: custom
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

# Health check's broken. App Engine calls /_ah/health 50 times/s regardless of the config settings
# Also the interval config is broken: https://issuetracker.google.com/issues/36024384
health_check:
  enable_health_check: False

env_variables:
  MEMCACHED: false
  STUB_HN: false
  CACHE_TTL: 60m
